<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jt</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^[^#]\s*.*:(\s*\[?| &amp;.+)?$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)</string>
	<key>keyEquivalent</key>
	<string>^~Y</string>
	<key>name</key>
	<string>JustText</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?&lt;!\$)(#)(?!\{).*$\n?</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.interpolated</string>
		</dict>
		<dict>
			<key>match</key>
			<!-- <string>»</string> -->
            <string>>></string>
			<key>name</key>
			<string>entity.other</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.txt</string>
	<key>uuid</key>
	<string>12E96375-D59E-4ECB-B831-9846F9C6A2A0</string>
</dict>
</plist>
